openapi: 3.0.0
info:
  title: HelloWorld API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Restituisce un messaggio di benvenuto
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
