/*
File Processor API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProcessFilePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessFilePost200Response{}

// ProcessFilePost200Response struct for ProcessFilePost200Response
type ProcessFilePost200Response struct {
	Result *string `json:"result,omitempty"`
}

// NewProcessFilePost200Response instantiates a new ProcessFilePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessFilePost200Response() *ProcessFilePost200Response {
	this := ProcessFilePost200Response{}
	return &this
}

// NewProcessFilePost200ResponseWithDefaults instantiates a new ProcessFilePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessFilePost200ResponseWithDefaults() *ProcessFilePost200Response {
	this := ProcessFilePost200Response{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ProcessFilePost200Response) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessFilePost200Response) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ProcessFilePost200Response) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *ProcessFilePost200Response) SetResult(v string) {
	o.Result = &v
}

func (o ProcessFilePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessFilePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableProcessFilePost200Response struct {
	value *ProcessFilePost200Response
	isSet bool
}

func (v NullableProcessFilePost200Response) Get() *ProcessFilePost200Response {
	return v.value
}

func (v *NullableProcessFilePost200Response) Set(val *ProcessFilePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessFilePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessFilePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessFilePost200Response(val *ProcessFilePost200Response) *NullableProcessFilePost200Response {
	return &NullableProcessFilePost200Response{value: val, isSet: true}
}

func (v NullableProcessFilePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessFilePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


